### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by sidonaldson** [dim912/handlebar-pretty-json#1]
Hi, Nice package!

Only issue is the horrid font. On my map it's some really weird italic font.

Maybe replace it with a monospaced font stack like this?

```
font-family: "Courier New", Courier, "Lucida Sans Typewriter", "Lucida Typewriter", monospace;
```

Taken from [https://www.cssfontstack.com/Courier-New](https://www.cssfontstack.com/Courier-New)

**Comment by dim912** [comment]
OK Thanks for the comment sidonaldson. I will fix it in next release.

**Comment by dim912** [comment]
Hello. 
The module applies a default css class of the formatted json. Anyway you can get json formatted(without applying css by calling like prettyJson(handlebars,true). // when the second parameter in the function call is true => module does not apply any css.

Anyway you can write your own styling for the formatted response.

Ex : 
`pre {
            font-family: cursive;
            background-color: #c8cccf;;
            outline: 0px solid #ccc;
            padding: 5px;
            margin: 5px;
            color: #6d6868;;
        }
      '
